// Stub header for liblogosdelivery - provides the same declarations as the real
// header (generated by the logos-delivery Nim build) so that
// delivery_module_plugin.cpp compiles during unit tests without the real library.

#ifndef LIBLOGOSDELIVERY_H
#define LIBLOGOSDELIVERY_H

#include <stddef.h>

#define RET_OK  0
#define RET_ERR 1

#ifdef __cplusplus
extern "C" {
#endif

typedef void (*logosdelivery_callback)(int callerRet, const char* msg, size_t len, void* userData);

// Create a new delivery node from a JSON config string.
// Returns a non-null context pointer on success; null on failure (callback fired with error).
void* logosdelivery_create_node(const char* cfg, logosdelivery_callback cb, void* userData);

// Register a persistent event callback for async node events (message_received, etc.).
void logosdelivery_set_event_callback(void* ctx, logosdelivery_callback cb, void* userData);

// Destroy a delivery context.
int logosdelivery_destroy(void* ctx, logosdelivery_callback cb, void* userData);

// Start the delivery node. Callback called on completion.
int logosdelivery_start_node(void* ctx, logosdelivery_callback cb, void* userData);

// Stop the delivery node. Callback called on completion.
int logosdelivery_stop_node(void* ctx, logosdelivery_callback cb, void* userData);

// Send a message. msg is a JSON string with contentTopic, payload (base64), and ephemeral fields.
// Callback returns a request ID string on success.
int logosdelivery_send(void* ctx, logosdelivery_callback cb, void* userData, const char* msg);

// Subscribe to a content topic. Callback called on completion.
int logosdelivery_subscribe(void* ctx, logosdelivery_callback cb, void* userData, const char* topic);

// Unsubscribe from a content topic. Callback called on completion.
int logosdelivery_unsubscribe(void* ctx, logosdelivery_callback cb, void* userData, const char* topic);

// Retrieve a named node info attribute. Callback returns the value string.
int logosdelivery_get_node_info(void* ctx, logosdelivery_callback cb, void* userData, const char* attributeName);

// Retrieve the list of available node info attribute IDs.
int logosdelivery_get_available_node_info_ids(void* ctx, logosdelivery_callback cb, void* userData);

// Retrieve available configuration parameter descriptions.
int logosdelivery_get_available_configs(void* ctx, logosdelivery_callback cb, void* userData);

typedef int (*EligibilityVerifierCb)(
    const char* proof_hex,
    const char* canonical_hex,
    const char* requester_peer_id,
    char* out_desc,
    size_t out_desc_len,
    void* user_data);

typedef int (*EligibilityProviderCb)(
    const char* canonical_hex,
    const char* provider_peer_id,
    char* out_proof_hex,
    size_t out_buf_len,
    void* user_data);

int logosdelivery_set_eligibility_verifier(void* ctx, EligibilityVerifierCb cb, void* user_data);

int logosdelivery_set_eligibility_provider(void* ctx, EligibilityProviderCb cb, void* user_data);

int logosdelivery_store_query(
    void* ctx,
    logosdelivery_callback cb,
    void* userData,
    const char* queryJson,
    const char* providerAddr);

#ifdef __cplusplus
}
#endif

#endif /* LIBLOGOSDELIVERY_H */
